### PR TITLE
Update README.md

### LINKED ISSUE #106: Typo in README on how to import all modules
When I include 'com.github.vestrel00.contacts-android:0.1.7' dependency and maven repository, Android Studio warns me that it "Failed to resolve". 

But when I include 'com.github.vestrel00.contacts-android:core:0.1.7', it works.

### PR DESCRIPTION
**Pull request by misha-n-ka**
Closes #106

### CODE REVIEW

**Comment by vestrel00** [comment]
Thank you for filing the issue and making the fix!!!

Please know that this PR is a pretty big deal for two reasons;

1. The line of documentation you fixed super important. It is the first thing that consumers will ever write when they try to use this library. If they copy-paste it and see that it doesn't work for them, they may just not bother at all with the library. They may even assume that everything in the library is poor quality. This is really bad!

2. You are the first contributor to this library! Welcome and thank you =)

You just made this library that much better! Who knows how many potential consumers this library has lost because of this typo. Really, I mean it!

**Review by vestrel00 — APPROVED** [review]
Thank you so much!!!

**Comment by vestrel00** [comment]
@misha-n-ka, I approved the PR. Please merge whenever you can =)

**Comment by misha-n-ka** [comment]
> @misha-n-ka, I approved the PR. Please merge whenever you can =)

**Comment by misha-n-ka** [comment]
> @misha-n-ka, I approved the PR. Please merge whenever you can =)

Thank you!

**Comment by vestrel00** [comment]
@misha-n-ka, I added you as a collaborator in case you are having issues merging this PR. I'm still trying to figure out how permissions work in GitHub.

**Pull request merged**
